<script>
  import "../lib/scss/custom.scss";
</script>

<div class="app">
  <main>
    <slot />
  </main>
  <div class="modal" id="disclaimer" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Disclaimer</h5>
        </div>
        <div class="modal-body">
          <p>This tool is provided for general information only.</p>
          <p>
            The State of Victoria provides no warranty or guarantee and makes no
            representation that the information contained in this tool is
            current, accurate, complete, without flaw of any kind or is suitable
            for your particular purposes.
          </p>
          <p>
            You must not rely on this tool for any general or specific purpose,
            including as a statement of government policy (except where clearly
            stated). You are responsible for assessing whether the information
            generated by this tool is accurate, complete or suitable and you
            should seek your own independent professional advice.
          </p>
          <p>
            To the extent permitted by law, the State of Victoria disclaims
            liability for any error, loss, damages, costs or other consequence
            caused by the use or reliance on information contained in this tool.
            The State of Victoria reserves the right to amend or withdraw this
            publication as required and without notice.
          </p>
        </div>
        <div class="modal-footer">
          <button
            type="button"
            class="btn btn-secondary"
            data-bs-dismiss="modal"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  </div>
  <footer>
    <div class="container">
      <div class="col pt-5 text-center">
        <p class="text-centre">
          <a
            data-bs-toggle="modal"
            data-bs-target="#disclaimer"
            href="#disclaimer"
          >
            Disclaimer
          </a>
          |
          <a href="https://agriculture.vic.gov.au/export/traceability">
            Back to Agriculture Victoria 🡕
          </a>
        </p>
      </div>
    </div>
  </footer>
</div>
